#!/bin/dash

# make sure .pushy existing
 if [ ! -d ".pushy" ]; then 
    echo "create a initial .pushy files first" >&2
    exit 1
    fi

#check if it commits
if [ ! -d  ".pushy/commits" ] || [ -z "$(ls -A .pushy/commits)" ]; then 
    echo "pushy-log : commit directory not found" >&2
    exit 1
    fi 

#make a loop for directories
for dir in .pushy/commits/* ; do
    commit_num=$(echo "$dir"|cut -d'/' -f3)
    commit_msg=$(cat "$dir/commit_message")
    echo "$commit_num $commit_msg"
done | sort -n -r
