#!/bin/dash
#setup the variblies 
a_select=false
Index_d=".pushy/index"
Commits_d=".pushy/commits"
commit_msg=''
commit_next_num=0
changes=0

# assumption 
if [ ! -d ".pushy" ]; then
    echo "Error: .pushy directory hasn't been created yet" >&2
    exit 1
fi

if [ ! -d "$Commits_d" ]; then
    mkdir -p "$Commits_d"
fi

while [ $# -gt 0 ]; do
    case "$1" in
        -a)
            a_select=true
            shift
            ;;
        -m)
            shift
            commit_msg="$1"
            break
            ;;
        *)
            echo "Usage: $0 [-a] -m <commit_message>"
            exit 1
            ;;
    esac
done

if [ -z "$commit_msg" ]; then
    echo "Error: Commit message is required."
    exit 1
fi

if [ -d "$Commits_d" ]; then
    commit_last_num=$(ls "$Commits_d/" | sort -rn | head -n 1)
    if [ ! -z "$commit_last_num" ]; then
        commit_next_num=$((commit_last_num + 1))
    fi
fi

if $a_select; then
    for files in $(ls); do
        if [ -f "$files" ]; then
            cp "$files" "$Index_d/$files"
            changes=1
        fi
    done  
fi

for file in $Index_d/*; do
    file_name=$(basename "$file") 
    if [ -f "$Index_d/$file_name" ]; then  
        current_sha1sum=$(sha1sum "$Index_d/$file_name" | cut -d ' ' -f1) 
        if [ -f "$Index_d/$file_name.sha1" ]; then  
            last_sha1sum=$(cat "$Index_d/$file_name.sha1")
            if [ "$current_sha1sum" != "$last_sha1sum" ]; then
                changes=1
                break
            
            fi
        else 
            changes=1
            break
        fi

    fi
done


if [ $changes -eq 0 ]; then
    echo "Nothing to commit."
    exit 0

else
    mkdir -p "$Commits_d/$commit_next_num"
    if [ "$(ls -A $Index_d)" ]; then
        cp $Index_d/* "$Commits_d/$commit_next_num/"
    fi
    echo "$commit_msg" > "$Commits_d/$commit_next_num/commit_message"
    echo "Committed as commit $commit_next_num"
fi
